import "./globals.css";
import { Roboto } from "next/font/google";
// Components
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Script from "next/script";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="dark:bg-gray-900">
          <Navbar />
          {children}
          <Footer />
        </main>
        <Script id="theme-switcher" strategy="beforeInteractive">
          {`
          if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }`}
        </Script>
      </body>
    </html>
  );
}
