import "./globals.css";
import { Inter } from "next/font/google";
// Components
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="dark:bg-cyan-900">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
